--CREATE TABLE `ORDER`(
--    id BIGINT PRIMARY KEY AUTO_INCREMENT,
--    total DECIMAL(10,2) NOT NULL,
--    quantity BIGINT NOT NULL,
--    placed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    customer_id BIGINT,
--    event_id BIGINT,
--    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL
--    FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE SET NULL
--)